// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjqmysaguglbeegbfnpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqcW15c2FndWdsYmVlZ2JmbnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTA5ODUsImV4cCI6MjA2NTQ4Njk4NX0.p-3gQKVv933W9wcQi-4NuSZIHwfjT1zZrp8nlPWngGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);